[package]
name = "aoc2025"
version = "0.1.0"
edition = "2021"
default-run = "aoc2024"

[dependencies]

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"

[[bench]]
name = "bench"
harness = false
